server:
  port: 8888

spring:
  application:
    name: configtest-dev
  config:
    import: optional:configserver:http://localhost:9900

---
management:
  endpoint:
    web:
      exposure:
        include: refresh